### ISSUE TITLE
Spine Distortion

### ISSUE THREAD

**Issue by mayaramamurthy** [Spineducation/Spineducation#21]
- [ ] Look into spine distortion

- [ ] Spine is separated...why??

- [ ] Try in autodesk

**Comment by katrinerachitsky** [comment]
Need to add pieces of spine together, and possibly add some outline / extra shading? hard to discern parts of spine from each other

**Comment by katrinerachitsky** [comment]
spine is no longer distorted, not separated, and has proper texture and colouring
