### ISSUE TITLE
Spine appears on touch

### ISSUE THREAD

**Issue by katrinerachitsky** [Spineducation/Spineducation#29]
Spine should appear and disappear upon touch

**Comment by katrinerachitsky** [comment]
also should always show up in the same position (should not show up one time back-front view and another side view - should ask Colby preferable view)

**Comment by mayaramamurthy** [comment]
- [ ] Still need to look into correct orientation if invalid

- [ ] Spine does not show up on first click -> touch is registered but nothing happens

**Comment by katrinerachitsky** [comment]
spine appears on touch, and any additional touches result in spine appearing in newly selected region in front of user
